name: Android CI

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive debug.apk
      uses: actions/upload-artifact@v3
      with:
        name: asteroidossync-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
